project:
  type: website

website:
  title: "Simple Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: about
      - href: slides/slides.ipynb
        text: Slides

format:
  html:
    theme: flatly
    toc: true
    mermaid: {}
bibliography: reference.bib


